Repository Surajdoberiyal/college-website, pull requests merged in 2023-10, with the labels that each got.

#2 Update index.html
  index.html
Labels: hacktoberfest-accepted

#1 meaningfull comments on css import
  index.html
Labels: hacktoberfest-accepted, contributor

#4 Update about-us.html
  About-us/about-us.html
Labels: hacktoberfest-accepted, hacktoberfest
